name: PretparkCore
version: 1.0
description: PretparkCore
author: Cooltimmetje
main: me.Cooltimmetje.PretparkCore.Main
commands:
    fixgamemodes:
        description: fixgamemodes
    coins:
        description: coins
    resetinv:
        description: resetinv
    givecoins:
        description: givecoins
    masscoins:
        description: masscoins
    setcoins:
        description: setcoins
    takecoins:
        description: takecoins
    fw:
        description: fw
    fwr:
        description: fwr
    listrides:
        description: listrides
    changeride:
        description: changeride
    reloadrides:
        description: reloadrides